"""enhance_models

Revision ID: 4521c59e6364
Revises: b69d4c08c73c
Create Date: 2026-05-21 05:49:35.358445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4521c59e6364'
down_revision: Union[str, None] = 'b69d4c08c73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('celery_jobs', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.add_column('celery_jobs', sa.Column('queue_name', sa.String(length=100), nullable=True))
    op.add_column('celery_jobs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('progress', 'completed_topics',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.create_unique_constraint('uq_progress_user_roadmap', 'progress', ['user_id', 'roadmap_id'])
    op.add_column('roadmaps', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('roadmaps', 'content',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.add_column('usage_limits', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_column('usage_limits', 'updated_at')
    op.alter_column('roadmaps', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('roadmaps', 'is_public')
    op.drop_constraint('uq_progress_user_roadmap', 'progress', type_='unique')
    op.alter_column('progress', 'completed_topics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('celery_jobs', 'error_message')
    op.drop_column('celery_jobs', 'queue_name')
    op.drop_column('celery_jobs', 'task_id')
    op.drop_column('ai_logs', 'error_message')
    # ### end Alembic commands ###
